str = 'Taras'                       # String type (prototype of class 'str')
bool = True                         # Bool type (prototype of class 'bool')
int = 10                            # Integer type (prototype of class "int")
float = 3.34                        # Float type (prototype of class "float")
list = [1, 2, 3, '5']               # List type (prototype of class "list")
dict = {'a': 1, 'b': 2, 'f4': 67}   # Dictionary type (prototype class "dict")
tuple = (3, 4, 5)                   # Tuple type (prototype of class "tuple")
set = {1, 2, 3, 4}                  # Set type (prototype of class "set")
range = range(100)                  # Range type (prototype of class "range")

print(list[2])
print(dict["a"])
